channels:
  - conda-forge
dependencies:
  - netcdf4=1.5.7
  - cartopy=0.18.0
  - ffmpeg=4.3.2
  - matplotlib=3.4.2
  - metpy=1.1.0
  - numpy=1.20.3
  - pip:
    - arm-pyart==1.11.6
    - boto3==1.20.34
    - botocore==1.23.34
    - siphon==0.9
